---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sarapnlc/public_html/old.sarahrosehassan.com
    - /bin/cp -R * $DEPLOYPATH
    - /bin/find $DEPLOYPATH -type f -exec chmod 644 {} \;
    - /bin/find $DEPLOYPATH -type d -exec chmod 755 {} \;
