---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sarapnlc/public_html/old.sarahrosehassan.com
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/rsync -av --delete --exclude ".git" --exclude ".cpanel.yml" ./ $DEPLOYPATH/
    - /bin/find $DEPLOYPATH -type f -exec chmod 644 {} \;
    - /bin/find $DEPLOYPATH -type d -exec chmod 755 {} \;
    - /bin/chmod 755 $DEPLOYPATH
    - /bin/chown -R sarapnlc:sarapnlc $DEPLOYPATH
